apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
spec:
  releaseName: vector
  chart:
    spec:
      chart: vector-agent
      sourceRef:
        kind: HelmRepository
        name: timberio
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:

    global:
      vector:
        commonEnvKV:
          RUST_BACKTRACE: "1"
          RUST_LOG: debug

    sinks:
      stdout:
        type: console
        inputs: ["kubernetes_logs"]
        rawConfig: |
          target = "stdout"
          encoding.codec = "json"
