apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-grafana-gp2
parameters:
  fsType: ext4
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
