apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
spec:
  releaseName: vector
  chart:
    spec:
      chart: vector
      version: ">0.0.0-0" # same as "latest" version with the `--devel` flag
      sourceRef:
        kind: HelmRepository
        name: timberio-nightly
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:

    global:
      vector:
        commonEnvKV:
          RUST_BACKTRACE: "1"

    vector-agent:

      prometheusSink:
        podMonitor:
          enabled: true

    vector-aggregator:

      prometheusSink:
        podMonitor:
          enabled: true

      sinks:

        stdout:
          type: console
          inputs: ["vector"]
          rawConfig: |
            target = "stdout"
            encoding.codec = "json"

        elasticsearch:
          type: elasticsearch
          inputs: ["vector"]
          rawConfig: |
            endpoint = "${ELASTICSEARCH_ENDPOINT}"
