apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  valuesFrom:
    # We assume this `ConfigMap` to be injected by terraform.
    - kind: ConfigMap
      name: terraform-injected-values
      valuesKey: helm-chart-values.yaml

  values:

    vector-aggregator:

      env:
        - name: ELASTICSEARCH_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: terraform-injected-values
              key: elasticsearch_endpoint

      extraVolumes:
        - name: terraform-injected-values
          configMap:
            name: terraform-injected-values
