apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector
  namespace: vector
spec:
  valuesFrom:
    # We assume this `ConfigMap` to be injected by terraform.
    - kind: ConfigMap
      name: terraform-injected-values
      valuesKey: helm-chart-values.yaml

